all:
    gcc ex2.c -lcrypto -o ex2
    echo tuicafacepedesteaptahopadoipasiladreapta >> file1.txt
    echo tuicafacepedesteaptahopadoipasiladreaptu >> file2.txt
    touch hash1_md5
    touch hash2_md5
    touch hash1_sha256
    touch hash2_sha256
    ./ex2 file1.txt file2.txt


